### ISSUE TITLE
Missed a few items

### ISSUE THREAD

**Issue by JimLiu** [jesselau76/srt-gpt-translator#1]
[ma.srt.txt](https://github.com/jesselau76/srt-gpt-translator/files/11128221/ma.srt.txt)
[ma_translated.srt.txt](https://github.com/jesselau76/srt-gpt-translator/files/11128222/ma_translated.srt.txt)

I used a subtitle file of 724 entries and ended up with 648 entries, which is still a bit less.

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/648674/229260904-0aa85a8e-220d-4b32-8da6-c4e2f31e8968.png">

**Comment by JimLiu** [comment]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/648674/229261761-45730d15-a231-45f1-9133-0daebe70c33c.png">

**Comment by jesselau76** [comment]
Got it. I forgot to add "\n" to each short text translation results.
