### ISSUE TITLE
SRT format error

### ISSUE THREAD

**Issue by Wangmengguo** [jesselau76/srt-gpt-translator#2]
211
00:11:22,000 --> 00:11:25,000
我记不得他的名字了，他现在怎么样了？

212
00:11:25,000 -> 00:11:27,000
走吧，雪伊，我们得告诉别人。

213
00:11:36,000 -> 00:11:38,000
船长，还没有任何消息。

214
00:11:39,000 -> 00:11:42,000
噢，我有些担心。他出发已经两个小时了。

215
00:11:42,000 -> 00:11:45,000
我们只能等待，等待避难所、飞机或风暴过去。

216
00:11:55,000 -> 00:11:57,000
这太疯狂了。

正确格式为211，即--> ，后续都少了一个-

不知道是什么缘故

**Comment by Wangmengguo** [comment]
另一个错误，:（英文输入）会变成：（中文输入），导致无法被字幕软件识别

**Comment by jesselau76** [comment]
少一 -很奇怪，原字幕文件正确吗？

（英文输入）会变成：（中文输入），这个是什么意思？

**Comment by Wangmengguo** [comment]
原文件是正确的。所以感觉很奇怪。
后面其实就是半角和全角的区别，源文件都是对的。

**Comment by jesselau76** [comment]
哦，明白了。估计翻译时API自动转成全角了。我更新时解决

**Comment by jesselau76** [comment]
这次应解决了。
