### ISSUE TITLE
如何生成中英双语字幕呢

### ISSUE THREAD

**Issue by xyh2132** [jesselau76/srt-gpt-translator#3]
如果需要中英文对照的双语,该如何配置运行命令?  这是刚需,对于学习语言的人来说,希望能得到解决

**Comment by jesselau76** [comment]
目前GPT-3.5 API不支持一句PROMPT生成双语。我看看有没其他办法

**Comment by sunlei** [comment]
试下这个方法看看：

- https://twitter.com/sunlei/status/1642595642462867457
- https://gist.github.com/sunlei/44f211cdf817c1373b4380e401161d17

**Comment by jesselau76** [comment]
谢谢。这个方法应该是可以的。不过我已经用传统方法解决了。可以省点usage
