### ISSUE TITLE
翻译后的中文字幕行问题

### ISSUE THREAD

**Issue by wuzimi** [jesselau76/srt-gpt-translator#4]
您好！今天测试了一个6分多钟的英文字幕翻译，翻译后的字幕存在以下问题：
1.打开翻译后的中文字幕时有错误提示，但是可以打开
![打开提示错误](https://user-images.githubusercontent.com/120776424/229768843-8889db75-c6ce-45bf-ba14-d090e370f876.jpg)

2.这是原字幕文件，一共159条字幕行，结束时间6分53秒，翻译后的中文字幕编程156条，并结束时间也缩短了几秒
![原字幕](https://user-images.githubusercontent.com/120776424/229769070-fac3e38e-960e-4eaa-887a-24b5dce3d394.jpg)

![翻译字幕](https://user-images.githubusercontent.com/120776424/229769283-4acb1c85-5eb2-4749-8ac6-4e795be45d63.jpg)
3.最后一个问题是，翻译的中文字幕行时间码从145到156时间接续不对，146后直接跳到了152，因为147的开始时间变成了比146更早的时间，下面几条标记红色的都有问题。

**Comment by jesselau76** [comment]
大概是openai api有一段罢工了。看来需要想个办法。

**Comment by jesselau76** [comment]
增加了检测openai返回结果的机制。如果不对应重试三次。三次还不行，就返回原文，跳过那一段短文本翻译。
